name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: '.'
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
